USE CSE_B_312

--1. DELETE ACCOUNT HOLDERS WHO OPENED ACCOUNT BEFORE DATE '1-DEC-96'
DELETE FROM DEPOSIT_DETAILS WHERE ADATE < '1-DEC-96'

--2. REMOVE BRANCHES WHO BELONG TO BOMBAY.
DELETE FROM BRANCH WHERE CITY = 'BOMBAY'

--3. REMOVE CITY WHICH BELONGS TO MADHURI AND PRAMOD.
DELETE FROM CUSTOMERS WHERE CNAME ='MADHURI' AND CNAME ='PRAMOD'

--4. REMOVE CUSTOMER NAME WHOSE AMMOUNT IS 2000 TO 7000 AND LOAN NUMBER
--IS 311.
DELETE FROM BORROW WHERE AMOUNT BETWEEN 2000 AND 7000	
AND LOANNO = '311'

--5. REMOVE CUSTOMER WHOSE CITY IS BARODA.
DELETE FROM CUSTOMERS WHERE CITY = 'BARODA'

--6. REMOVE CITY WHICH BLONGS TO EITHER NEHRU PLACE,CAHNDI OO POWAI.
DELETE FROM DEPOSIT_DETAILS WHERE BNAME = 'NEHRU PLACE' OR 
BNAME = 'CHANDI' OR BNAME = 'POWAI'

--7. REMOVE ALL BORROWERS WHOSE LOANNO IS NOT BETWEEN 205 TO 321.
DELETE FROM BORROW WHERE LOANNO IS NOT BETWEEN 205 AND 321

--8. 
DELETE FROM BRANCH WHERE BNAME IN('DELHI','BANGLORE')

--9.


